price_group:
  name:
    base: 'Base Rate'
    external: 'External Rate'
    cancer_center: 'Cancer Center Rate'

financial:
  # in the format MM-DD
  fiscal_year_begins: 09-01
  journal_format:
    xls: true
    csv: true
    xml: true

validator:
  class_name: ValidatorDefault
  test:
    factory: # relative to Rails.root
    helper: 'spec/validator_helper' # relative to Rails.root

email:
  from: 'noreply@example.com'
  fake:
    enabled: false
    to:
  exceptions:
    sender: 'noreply@example.com'
    recipients: [ 'warn@example.com', 'error@example.com' ]

order_details:
  # These hooks are triggered when an order detail enters into the status
  # The hooks can be configured with settings. Here are several formats you can use:
  #   new:
  #     - ApprovalNotification::NotifyPurchaser
  #     - ApprovalNotification::NotifyFacility
  #   inprocess: 
  #     - 
  #       class: ApprovalNotification::NotifyPurchaser
  #       setting_1: test3
  #     - ApprovalNotification::NotifyFacility
  #   completed: ApprovalNotification::NotifyPurchaser
  #   reconciled: ["ApprovalNotification::NotifyPurchaser", "ApprovalNotification::NotifyFacility"]
  status_change_hooks:
    pending_approval: StatusChangeNotifications::NotifyFacilityHook
    approved: StatusChangeNotifications::NotifyPurchaserHook    

billing:
  review_period: <%= 7.days %>

external_services:
  survey: Surveyor

#
# For these settings use SettingsHelper#feature_on?
feature:
  create_users_on: true
  password_update_on: true
  recharge_accounts_on: true
  expense_accounts_on: true
  edit_accounts_on: true
  suspend_accounts_on: true
  product_specific_contacts_on: true
